#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
# Initialize counter
count=1

# Loop until counter reaches 10
while [ $count -le 10 ]
do
    # Check if it's the 9th iteration
    if [ $count -eq 9 ]; then
        echo "Best School"
        echo "Hi"
    else
        echo "Best School"
    fi
    
    ((count++))
done
